---
# vim:ft=ansible:
- hosts: localhost
  connection: local
  vars:
    - ansible_python_interpreter: "/usr/bin/python2"
    - become: yes
  roles:
    - git     # Ubuntu, RHEL
    - opencv  # Ubuntu, RHEL
    - java    # Ubuntu
    - sbt     # Ubuntu
    - rust    # Ubuntu, RHEL
    - stack   # Ubuntu
    - node    # Ubuntu
#   - mongodb # RHEL
...
