---
# vim:ft=ansible:
# Installs OpenCV
# Confirmed to work on Ubuntu 14.04 (2016-03-29)
- name: Check if OpenCV is installed
  shell: /sbin/ldconfig -p | grep -i opencv
  become: yes
  ignore_errors: True
  changed_when: False
  register: libopencv
- name: Install Git (Ubuntu)
  apt:
    pkg: "git"
    update_cache: yes
  become: yes
  when: libopencv|failed and ansible_os_family == "Debian"
- name: Install Git (RedHat)
  yum:
    name: "git"
    update_cache: yes
  become: yes
  when: libopencv|failed and ansible_os_family == "RedHat"
- name: Clone Install-OpenCV
  git:
    repo: "https://github.com/jayrambhia/Install-OpenCV.git"
    dest: "/opt/Install-OpenCV"
  when: libopencv|failed
- name: Install OpenCV (Ubuntu)
  shell:
    ./opencv_latest.sh
  args:
    chdir: "/opt/Install-OpenCV/Ubuntu"
  become: yes
  when: libopencv|failed and ansible_os_family == "Debian"
- name: Install OpenCV (RedHat)
  shell:
    ./opencv_latest.sh
  args:
    chdir: "/opt/Install-OpenCV/RedHat"
  become: yes
  when: libopencv|failed and ansible_os_family == "RedHat"
...
