---
# vim:ft=ansible:
# For RHEL7
# Require reboot after running this script to prevent a warning message from appearing
- hosts: localhost
  vars:
    - ansible_ssh_user: "{{ my_user }}"
    - ansible_ssh_private_key_file: "{{ my_private_key }}"
  become: yes
  become_user: root
  tasks:
  - name: Copy mongodb-org-3.2.repo
    copy:
      src: ../conf/mongodb-org-3.2.repo
      dest: /etc/yum.repos.d/mongodb-org-3.2.repo
      owner: root
      group: root
  - name: Yum update
    yum:
      name: "*"
      state: latest
  - name: Install MongoDB
    yum:
      name: mongodb-org
      enablerepo: "mongodb-org-3.2"
  - name: Start MongoDB
    service:
      name: mongod
      state: started
    changed_when: False
  # https://docs.mongodb.org/v3.0/tutorial/transparent-huge-pages/
  - name: Copy init.d script
    copy:
      src: ../conf/disable-transparent-hugepages
      dest: /etc/init.d/disable-transparent-hugepages
      force: no
  - name: Make it executable
    file:
      path: /etc/init.d/disable-transparent-hugepages
      owner: root
      group: root
      mode: 755
  - name: Configure to run it on boot
    shell: chkconfig --add disable-transparent-hugepages
    changed_when: False
  - name: Create a directory /etc/tuned/no-thp
    file:
      path: /etc/tuned/no-thp
      state: directory
      owner: root
  - name: Copy init.d script
    copy:
      src: ../conf/tuned.conf
      dest: /etc/tuned/no-thp/tuned.conf
      force: no
  - name: Enable the new profile
    shell: tuned-adm profile no-thp
    changed_when: False
  - name: Edit limits.conf (hard nproc 32000)
    lineinfile:
      line: "mongod hard nproc 32000"
      insertbefore: "# End of file"
      dest: /etc/security/limits.conf
  - name: Edit limits.conf (soft nproc 32000)
    lineinfile:
      line: "mongod soft nproc 32000"
      insertbefore: "# End of file"
      dest: /etc/security/limits.conf
  - name: Edit limits.conf (hard nofile 64000)
    lineinfile:
      line: "mongod hard nofile 64000"
      insertbefore: "# End of file"
      dest: /etc/security/limits.conf
  - name: Edit limits.conf (hard nofile 64000)
    lineinfile:
      line: "mongod hard nofile 64000"
      insertbefore: "# End of file"
      dest: /etc/security/limits.conf
  - name: Restart MongoDB
    service:
      name: mongod
      state: restarted
    changed_when: False
...
