---
# vim:ft=ansible:
# Install Node.js and related packages
- name: Check if "n" is installed
  shell: "/usr/local/bin/n --version"
  register: node
  ignore_errors: True
  changed_when: False
  become: yes
- name: Install Node.js and npm
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - "nodejs"
    - "npm"
  become: yes
  when: node|failed
- name: Install "n"
  shell: "n stable"
  become: yes
  when: node|failed
...
