"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false

[username]
show_always = true

[directory]
truncate_to_repo = false

[nodejs]
symbol = "nodejs "

[cmd_duration]
disabled = true
